version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app  # Mounts the current directory into the container
    command: uvicorn app:app --host 0.0.0.0 --port 7860 --reload
